on: [push, pull_request]

name: Check schemas

env:
  AJV_CLI_VERSION: 4.0.1
  NPM_CONFIG_PREFIX: "~/.npm-global"

jobs:
  check-schemas:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: Add .npm-global to PATH
        run: echo "${NPM_CONFIG_PREFIX}/bin" >> $GITHUB_PATH

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install ajv-cli
        run: |
          npm install -g ajv-cli@${AJV_CLI_VERSION}

      - name: Compile mini-schemas
        run: |
          ajv compile -s "terms/*/*.json" --strict=false

      - name: Check for non-ascii characters
        run: |
          if grep -R -P -l "[^\x00-\x7F]" ./terms/; then
            exit 1
          else
            exit 0
          fi
